import { MedusaService } from "@medusajs/framework/utils"
import { ClinicStaff } from "./models/clinic-staff"
import OrderWorkflow from "./models/order-workflow"
import ProductTreatmentMap from "./models/product-treatment-map"
import { ClinicUiConfig } from "./models/clinic-ui-config"

// ── Status constants ────────────────────────────────────────────────────────
export const ORDER_STATUS = {
  AWAITING_PROVIDER_REVIEW: "awaiting_provider_review",
  PROVIDER_APPROVED:        "provider_approved",
  PROVIDER_DEFERRED:        "provider_deferred",
  MD_APPROVED:              "md_approved",
  MD_DENIED:                "md_denied",
  SENT_TO_PHARMACY:         "sent_to_pharmacy",
  PHARMACY_PROCESSING:      "pharmacy_processing",
  SHIPPED:                  "shipped",
  REFUND_ISSUED:            "refund_issued",
} as const

export type OrderStatus = typeof ORDER_STATUS[keyof typeof ORDER_STATUS]

export const STATUS_LABELS: Record<OrderStatus, string> = {
  awaiting_provider_review: "Awaiting Provider Review",
  provider_approved:        "Provider Approved",
  provider_deferred:        "Under Medical Director Review",
  md_approved:              "MD Approved",
  md_denied:                "Denied — Refund Issued",
  sent_to_pharmacy:         "Sent to Pharmacy",
  pharmacy_processing:      "Pharmacy Processing",
  shipped:                  "Shipped",
  refund_issued:            "Refund Issued",
}

// ── Service ────────────────────────────────────────────────────────────────
class ClinicOpsService extends MedusaService({
  ClinicStaff,
  OrderWorkflow,
  ProductTreatmentMap,
  ClinicUiConfig,
}) {

  // ── UI CONFIGURATION ──────────────────────────────────────────────────────

  async getUiConfigByTenant(tenantDomain: string) {
    const results = await this.listClinicUiConfigs({ 
      tenant_domain: tenantDomain 
    })
    return results[0] ?? null
  }

  async upsertUiConfig(data: {
    tenant_domain: string
    nav_links?: Record<string, unknown> | null
    footer_links?: Record<string, unknown> | null
    logo_url?: string | null
    get_started_url?: string | null
  }) {
    // 1. Manually check for existing config to bypass the missing factory method
    const existing = await this.listClinicUiConfigs({ 
      tenant_domain: data.tenant_domain 
    })

    if (existing.length > 0) {
      // 2. Use the standard plural update method generated by the factory
      return await this.updateClinicUiConfigs(
        { id: existing[0].id }, 
        data
      )
    }

    // 3. Use the standard plural create method generated by the factory
    return await this.createClinicUiConfigs(data)
  }

  // ── STAFF ─────────────────────────────────────────────────────────────────

  async getStaffForTenant(tenantDomain: string) {
    return this.listClinicStaffs({ tenant_domain: tenantDomain, is_active: true })
  }

  async getStaffByRole(tenantDomain: string, role: string) {
    return this.listClinicStaffs({ tenant_domain: tenantDomain, role, is_active: true })
  }

  async addStaff(data: {
    tenant_domain: string
    user_id: string
    email: string
    full_name?: string
    role: "clinic_admin" | "medical_director" | "pharmacist"
  }) {
    return this.createClinicStaffs(data)
  }

  async deactivateStaff(staffId: string) {
    return this.updateClinicStaffs({ id: staffId }, { is_active: false })
  }

  async getUserRole(userId: string, tenantDomain: string): Promise<string | null> {
    const results = await this.listClinicStaffs({
      user_id: userId,
      tenant_domain: tenantDomain,
      is_active: true,
    })
    return results[0]?.role ?? null
  }

  // ── ORDER WORKFLOW ────────────────────────────────────────────────────────

  async createWorkflow(data: {
    order_id: string
    tenant_domain: string
    patient_id?: number
    gfe_id?: number
    room_no?: number
    virtual_room_url?: string
  }) {
    return this.createOrderWorkflows({
      ...data,
      status: ORDER_STATUS.AWAITING_PROVIDER_REVIEW,
    })
  }

  async getWorkflowByOrderId(orderId: string) {
    const results = await this.listOrderWorkflows({ order_id: orderId })
    return results[0] ?? null
  }

  async getWorkflowsByTenant(tenantDomain: string, status?: OrderStatus) {
    const filter: Record<string, any> = { tenant_domain: tenantDomain }
    if (status) filter.status = status
    return this.listOrderWorkflows(filter)
  }

  async applyProviderDecision(
    orderId: string,
    decision: "approved" | "defer",
    providerName: string
  ) {
    const newStatus = decision === "approved"
      ? ORDER_STATUS.PROVIDER_APPROVED
      : ORDER_STATUS.PROVIDER_DEFERRED

    return this.updateOrderWorkflows(
      { order_id: orderId },
      {
        status: newStatus,
        provider_status: decision,
        provider_name: providerName,
        provider_reviewed_at: new Date(),
      }
    )
  }

  async applyMdDecision(
    orderId: string,
    mdUserId: string,
    decision: "approved" | "denied",
    notes?: string
  ) {
    const newStatus = decision === "approved"
      ? ORDER_STATUS.MD_APPROVED
      : ORDER_STATUS.MD_DENIED

    return this.updateOrderWorkflows(
      { order_id: orderId },
      {
        status: newStatus,
        md_user_id: mdUserId,
        md_decision: decision,
        md_notes: notes ?? null,
        md_reviewed_at: new Date(),
      }
    )
  }

  async sendToPharmacy(orderId: string) {
    const workflow = await this.getWorkflowByOrderId(orderId)
    if (!workflow) throw new Error(`No workflow for order ${orderId}`)

    const allowedStatuses: OrderStatus[] = [
      ORDER_STATUS.PROVIDER_APPROVED,
      ORDER_STATUS.MD_APPROVED,
    ]
    if (!allowedStatuses.includes(workflow.status as OrderStatus)) {
      throw new Error(`Order ${orderId} cannot be sent to pharmacy from status: ${workflow.status}`)
    }

    return this.updateOrderWorkflows(
      { order_id: orderId },
      { status: ORDER_STATUS.SENT_TO_PHARMACY }
    )
  }

  async markPharmacyProcessing(orderId: string, pharmacistUserId: string, notes?: string) {
    return this.updateOrderWorkflows(
      { order_id: orderId },
      {
        status: ORDER_STATUS.PHARMACY_PROCESSING,
        pharmacist_user_id: pharmacistUserId,
        pharmacy_notes: notes ?? null,
      }
    )
  }

  async markShipped(
    orderId: string,
    pharmacistUserId: string,
    trackingNumber: string,
    carrier: string
  ) {
    return this.updateOrderWorkflows(
      { order_id: orderId },
      {
        status: ORDER_STATUS.SHIPPED,
        pharmacist_user_id: pharmacistUserId,
        tracking_number: trackingNumber,
        carrier,
        shipped_at: new Date(),
      }
    )
  }

  async markRefundIssued(orderId: string, refundId: string) {
    return this.updateOrderWorkflows(
      { order_id: orderId },
      {
        status: ORDER_STATUS.REFUND_ISSUED,
        refund_id: refundId,
        refund_issued_at: new Date(),
      }
    )
  }

  async getPendingMdReview(tenantDomain: string) {
    return this.listOrderWorkflows({
      tenant_domain: tenantDomain,
      status: ORDER_STATUS.PROVIDER_DEFERRED,
    })
  }

  async getReadyForPharmacy(tenantDomain: string) {
    const [sent, processing] = await Promise.all([
      this.listOrderWorkflows({ tenant_domain: tenantDomain, status: ORDER_STATUS.SENT_TO_PHARMACY }),
      this.listOrderWorkflows({ tenant_domain: tenantDomain, status: ORDER_STATUS.PHARMACY_PROCESSING }),
    ])
    return [...sent, ...processing]
  }

  // ── PRODUCT → TREATMENT MAPPING ───────────────────────────────────────────

  async getMappingsForTenant(tenantDomain: string) {
    return this.listProductTreatmentMaps({ tenant_domain: tenantDomain })
  }

  async getMappingForProduct(tenantDomain: string, productId: string) {
    return this.listProductTreatmentMaps({
      tenant_domain: tenantDomain,
      product_id: productId,
    })
  }

  async upsertProductMapping(data: {
    tenant_domain: string
    product_id: string
    product_title?: string
    variant_id?: string
    treatment_id: number
    treatment_name?: string
    requires_eligibility?: boolean
  }) {
    const existing = await this.listProductTreatmentMaps({
      tenant_domain: data.tenant_domain,
      product_id: data.product_id,
      treatment_id: data.treatment_id,
    })

    if (existing.length > 0) {
      return this.updateProductTreatmentMaps(
        { id: existing[0].id },
        {
          treatment_name: data.treatment_name,
          product_title: data.product_title,
          requires_eligibility: data.requires_eligibility ?? true,
        }
      )
    }

    return this.createProductTreatmentMaps(data)
  }

  async removeProductMapping(mappingId: string) {
    return this.deleteProductTreatmentMaps({ id: mappingId })
  }

  async getTreatmentIdsForProducts(
    tenantDomain: string,
    productIds: string[]
  ): Promise<number[]> {
    const mappings = await this.listProductTreatmentMaps({
      tenant_domain: tenantDomain,
      product_id: productIds,
    })
    return [...new Set(mappings.map(m => m.treatment_id))]
  }

  async anyProductRequiresEligibility(
    tenantDomain: string,
    productIds: string[]
  ): Promise<boolean> {
    const mappings = await this.listProductTreatmentMaps({
      tenant_domain: tenantDomain,
      product_id: productIds,
      requires_eligibility: true,
    })
    return mappings.length > 0
  }
}

export default ClinicOpsService